project:
  type: website

website:
  title: "Vishal Mistri GIS Portfolio"
  sidebar:
    logo: assets/logo.svg
    tools:
      - icon: github
        href: https://github.com/vmistri91/Portfolio
    contents: 
      - social_atlas_weapons.qmd
      - map_presentation.qmd
      - maup_illustrated.qmd
  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: about.qmd
      - social_atlas_weapons.qmd
      - map_presentation.qmd 
      - maup_illustrated.qmd
      
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual