project:
  type: website

website:
  title: "Vishal Mistri GIS Portfolio"
  sidebar:
    logo: assets/logo.svg
    tools:
      - icon: github
        href: https://github.com/vmistri91/Portfolio
    contents: 
      - weapon_crime_social_atlas.qmd
  navbar:
    left:
      - href: weapon_crime_social_atlas.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual

